# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit

repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9007
    hooks:
      - id: style-files
      - id: lintr
        additional_dependencies:
          - r-lib/lintr
        exclude: >
          (?x)^(
          inst/.*|
          man/.*|
          tests/.*|
          vignettes/.*|
          )$
      - id: roxygenize
      - id: use-tidy-description
      - id: spell-check
        exclude: >
          (?x)^(
          .*\.[rR]|
          .*\.feather|
          .*\.jpeg|
          .*\.pdf|
          .*\.png|
          .*\.py|
          .*\.RData|
          .*\.rds|
          .*\.Rds|
          .*\.Rproj|
          .*\.sh|
          .*\.cpp|
          .*\.hpp|
          .*\.h|
          (.*/|)\.gitignore|
          (.*/|)\.gitlab-ci\.yml|
          (.*/|)\.lintr|
          (.*/|)\.pre-commit-.*|
          (.*/|)\.Rbuildignore|
          (.*/|)\.Renviron|
          (.*/|)\.Rprofile|
          (.*/|)\.travis\.yml|
          (.*/|)appveyor\.yml|
          (.*/|)NAMESPACE|
          (.*/|)renv/settings\.dcf|
          (.*/|)renv\.lock|
          (.*/|)WORDLIST|
          (.*/|)CRAN-SUBMISSION|
          \.github/workflows/.*|
          data/.*|
          )$
      - id: readme-rmd-rendered
      - id: parsable-R
      - id: pkgdown
      - id: deps-in-desc
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=200"]
      - id: check-yaml
      - id: mixed-line-ending
      - id: file-contents-sorter
        files: "\\.Rbuildignore$"
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
          \.Rd|
          )$
  - repo: https://github.com/lorenzwalthert/gitignore-tidy
    rev: 475bf5d96927a1887ce2863ff3075b1d7240bc51
    hooks:
      - id: tidy-gitignore
  - repo: local
    hooks:
      - id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.

ci:
  skip: [pkgdown]
  autoupdate_schedule: monthly
