on:
  pull_request:
    branches: [main]

name: enforce-version-increment

jobs:
  enforce-version-increment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - run: git checkout ${{ github.ref }}
      - run: export VERSION_PR=$(cat DESCRIPTION | grep Version: | cut -d\  -f 2)
      - run: git checkout main
      - run: export VERSION_MAIN=$(cat DESCRIPTION | grep Version: | cut -d\  -f 2)
      - name: Check version of PR > version of main
        run: Rscript -e 'if("$VERSION_PR" <= "$VERSION_MAIN") quit(status = 1)'
