on:
  pull_request:
    branches: [main]

name: enforce-version-increment

jobs:
  enforce-version-increment:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: actions/checkout@v3
      - run: echo "VERSION_PR=$(cat DESCRIPTION | grep Version | cut -d ' ' -f 2)" >> $GITHUB_ENV

      - run: echo $VERSION_PR

      - uses: actions/checkout@v3
        with:
          ref: main
      - run: echo "VERSION_MAIN=$(cat DESCRIPTION | grep Version | cut -d ' ' -f 2)" >> $GITHUB_ENV

      - run: echo $VERSION_PR > $VERSION_MAIN

      - name: Check version of PR > version of main
        run: Rscript -e 'if("$VERSION_PR" <= "$VERSION_MAIN") stop("PR must increment package version before merging to main.")'
