on:
  pull_request:
    branches: [main]

name: enforce-version-increment

jobs:
  enforce-version-increment:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: actions/checkout@v4
      - run: echo "VERSION_PR=$(cat DESCRIPTION | grep Version | cut -d ' ' -f 2)" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: main
      - run: echo "VERSION_MAIN=$(cat DESCRIPTION | grep Version | cut -d ' ' -f 2)" >> $GITHUB_ENV

      - name: Check version of PR > version of main
        run: |
          if (Sys.getenv("VERSION_PR") <= Sys.getenv("VERSION_MAIN")) {
            stop("PR must increment package version before it can merge to main.")
          }
        shell: Rscript {0}
